### ISSUE TITLE
Working great but can't get Apple Core / Haptics Plugins to work

### ISSUE THREAD

**Issue by antiero** [bdeweygit/unity-swiftui-demo#2]
I got this amazing example running - nice work dude! I then tried to add Apple's Unity Plugins to add haptics support from the Unity side, and getting framework not found errors when building in Xcode (I have got this working in standard iOS Unity builds, without Unity as a Library approach), . Any idea how/where these frameworks need to be added to the Xcode project to get them to load?
(https://forums.developer.apple.com/forums/tags/apple-unity-plug-ins)

**Comment by bdeweygit** [comment]
To make sure we are on the same page can you outline the steps I should follow to reproduce the build failure? And what the expected error message is?

**Comment by antiero** [comment]
1. Check out the Apple Core Unity plugins from here: https://github.com/apple/unityplugins/
2. `cd` into `unityplugins`, build the Core and Core Haptics via: `python3 build.py -p Core CoreHaptics` (you'll need to type: 'Y' a lot whilst building!)
3. Open your UnityProject, Package Manager > +  > 'Add Package from tarball' and select `com.apple.unityplugin.corehaptics-1.2.2.tgz` and `com.apple.unityplugin.core-3.1.5.tgz` from the `unityplugins/Build` folder
4. In Package Manager, select Apple.Core and click Import next to Apple.Core API Availability Demo
5. Open your SampleScene. Add a New GameObject Add Component > 'Availability Manager'
6. Build Settings > Switch to iOS Build Platform, build to Builds/iOS as before.
7. Open Xcode, sort out Codesigning/bundle identities as before.
8. Build UnitySwiftUI to a connected iPhone.

Result:
```

dyld[36273]: Library not loaded: @rpath/CoreHapticsWrapper.framework/CoreHapticsWrapper
  Referenced from: <EC855629-A1BE-399D-A97F-0FEF28CDE67F> /private/var/containers/Bundle/Application/4470DB5F-7CE3-44A5-A4E6-6C151BD0FB75/UnitySwiftUI.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: tried: '/private/var/containers/Bundle/Application/4470DB5F-7CE3-44A5-A4E6-6C151BD0FB75/UnitySwiftUI.app/Frameworks/CoreHapticsWrapper.framework/CoreHapticsWrapper' (no such file), '/private/var/containers/Bundle/Application/4470DB5F-7CE3-44A5-A4E6-6C151BD0FB75/UnitySwiftUI.app/Frameworks/UnityFramework.framework/Frameworks/CoreHapticsWrapper.framework/CoreHapticsWrapper' (no such file), '/private/var/containers/Bundle/Application/4470DB5F-7CE3-44A5-A4E6-6C151BD0FB75/UnitySwiftUI.app/Frameworks/CoreHapticsWrapper.framework/CoreHapticsWrapper' (no such file), '/private/var/containers/Bundle/Application/4470DB5F-7CE3-44A5-A4E6-6C151BD0FB75/UnitySwiftUI.app/CoreHapticsWrapper.framework/CoreHapticsWrapper' (no such file), '/private/var/containers/Bundle/Application/4470DB5F-7CE3-44A5-A4E6-6C151BD0FB75/UnitySwiftUI.app/Frameworks/CoreHapticsWrapper.framework/CoreHapticsWrapper' (no such file), '/private/var/containers/Bundle/Application/4470DB5F-7CE3-44A5-A4E6-6C151BD0FB75/UnitySwiftUI.app/CoreHapticsWrapper.framework/CoreHapticsWrapper' (no such file), '/private/var/containers/Bundle/Application/4470DB5F-7CE3-44A5-A4E6-6C151BD0FB75/UnitySwiftUI.app/Frameworks/CoreHapticsWrapper.framework/CoreHapticsWrapper' (no such file)
```

**Comment by bdeweygit** [comment]
I hit the same problem. This is a runtime error, not a build-time error.

It looks like the Apple Unity plugins add a build script whose job it is to embed the plugin frameworks into the generated Xcode project. You can find this script if you open up the integration workspace, select the Unity-iPhone target (this is the normal unity iOS target you _would_ build if you were not using UAAL), select Build Phases, and expand the "Embed Apple Plug-in Libraries" step to view the shell script. The integration does not build the Unity-iPhone target, it builds the UnityFramework target, so we need to copy this script over.

You could probably add some code to the `UnityProject/Assets/Editor/PostProcessBuild.cs` file to do this automatically, but to do it manually you can select the UnityFramework target, select Build Phases, click the plus icon to add a "New Run Script Phase". Then just copy paste the contents of that original script.

I recommend you first do Product > Clean Build Folder, and then give these steps a try. It worked for me.

**Comment by bdeweygit** [comment]
Alternatively, you could forgo the script and embed the frameworks manually:

1. Select UnityFramework target
2. Select General tab and expand Frameworks and Libraries
3. Click the plus icon > Add Other > Add Files
4. Navigate to `UnityProject/Builds/iOS/ApplePluginLibraries/Apple.Core/AppleCoreNative.framework` and click Open
5. Set it to Embed & Sign
6. Repeat the same for `Apple.CoreHaptics/CoreHapticsWrapper.framework`

The nice thing about the script is that it should always work regardless of which particular apple plugins you end up using.

**Comment by antiero** [comment]
Amazing thanks, will give this a try!

**Comment by antiero** [comment]
It built and ran! 🙌  I went with the Build Script option and will endeavour to get this into the PostProcessBuild.cs 🙂 I found that I also needed to do a Manual build of the UnityFramework, prior to the UnitySwiftUI building, to get this to work, and Interestingly Product > Clean Build Folder didn't work, but if I did 'Show Build Folder' and clear it manually, everything worked nicely, thanks so much for your help @bdeweygit - above and beyond! 🫡 

Out of interest, which Xcode Version were you using @bdeweygit ?

**Comment by antiero** [comment]
For interest @bdeweygit, I've created an example of how to add the Build Phase for Apple Plug-ins in to your [UnityProject/Assets/Editor/PostProcessBuild.cs](https://github.com/antiero/unity-swiftui/blob/main/UnityProject/Assets/Editor/PostProcessBuild.cs) script 🙂 

https://github.com/antiero/unity-swiftui/commit/1f5c8755bb38cd7d9e8e435e0706ba8ace571a08

Note: I found that to get this to work on Device, I had to manually build the UntiyFramework in the Unity-iPhone project first, before deploying UnitySwiftUI to device.

**Comment by bdeweygit** [comment]
I've been running Xcode 16.1. And I never had to rebuild the UnityFramework target on its own, although there have been times where I had to either clean the build folder or just restart Xcode. Xcode has long had problems with sometimes using cached builds rather than rebuilding from scratch as it _should_ do when you modify/save relevant files like that build phase step. You can also execute the Unity iOS build with one of two modes - [replace or append](https://docs.unity3d.com/6000.0/Documentation/Manual/iphone-BuildProcess.html#replace-and-append-mode). Maybe that also has some affect on how Xcode behaves? Maybe there is even a timing thing where you need to wait a minute for Xcode to recalibrate itself before it can rebuild correctly? If you find a very consistent way to make the whole edit > save > build/run workflow not work drop a comment; maybe there is something we can do about it.

As for your changes to `PostProcessBuild.cs`, the `PBXProject` class might have something that lets you ready/copy a build phase step from one target to another which would be cleaner than hardcoding the script as a string. This way it can stay up-to-date if a plugin upgrade includes changes to that script. But this is a small detail; your solution should work for a long time. Just be sure it is replacing that build phase step if it already exists rather than adding a duplicate.
