### ISSUE TITLE
Framerate limited to max 60fps?

### ISSUE THREAD

**Issue by antiero** [bdeweygit/unity-swiftui-demo#4]
I noticed that the framerate of the default app was quite low and felt a bit sluggish when dragging. Turns out that it defaults to 30fps. So I added the ability to change the Unity Application.targetFramerate with a slider from the SwiftUI side.

https://youtube.com/shorts/rsAl2FueVTE?si=P9tYVK97qyk93sgA

When building the App on an iPhone with Pro Motion (supporting up to 120fps), I found that the App seems to max out at 60fps. (Tested using the [Graphy](https://assetstore.unity.com/packages/tools/gui/graphy-ultimate-fps-counter-stats-monitor-debugger-105778?srsltid=AfmBOorJU62PPmrYf3Oh45iZReJHQ0xL2GkmvnTlBh18gYdoWpRZXUgZ) plugin) 

I've verified with other Unity apps that 120fps is reported with Graphy.

Is this an enforced limit with embedding Unity as a Library, or do you know if > 60fps is possible?

**Comment by bdeweygit** [comment]
I doubt it has anything to do with UAAL. If [the docs](https://docs.unity3d.com/ScriptReference/Application-targetFrameRate.html) are accurate, then on iOS and Android...

> content is rendered at fixed 30 fps to conserve battery power, independent of the native refresh rate of the display

The assumption is that mobile devices have poor battery and thermals, so 30fps is the sensible default for something as computationally intense as a game engine. To push the fps up to the iOS native refresh rate of 60Hz you are correct to use `Application.targetFramerate`.

The same docs say that to go even higher you need to explicitly opt-in to ProMotion. There should be an "Enable ProMotion Support" option in the [player settings](https://docs.unity3d.com/Manual/class-PlayerSettingsiOS.html). Have you turned it on? I think this player setting and the `Application.targetFrameRate` are the only things you can use to modulate the fps on iOS. People also try to mess around with the `QualitySettings.vSyncCount`, but the docs say that...

> Mobile platforms always ignore QualitySettings.vSyncCount

Obviously the device itself needs to support ProMotion and be in a battery/thermal state where it is willing to let the app utilize it.

**Comment by antiero** [comment]
Yes, I _had_ enabled ProMotion support in player settings... (I believe this just sets the CADisableMinimumFrameDuration+CADisableMinimumFrameDurationOnPhone booleans in the plist), but even with that enabled, the example App runs at 60fps. In another project I have ProMotion enabled (with non-SwiftUI<>Unity setup), this works (hits 120fps). Not a massive problem for now, but I was just wanting to benchmark performance of embedding Unity into the SwiftUI side of things :)

**Comment by bdeweygit** [comment]
The CADisableMinimumFrameDuration and CADisableMinimumFrameDurationOnPhone booleans are only being applied to the Unity-iPhone target's info plist, so we need to apply it to the UnitySwiftUI target and then it will work. Add them manually or use the PostProcessBuild.cs script.

Looks like CADisableMinimumFrameDurationOnPhone is the one that matters.
<img src="https://github.com/user-attachments/assets/8a1bbce2-e56d-4780-85be-bb2561d06b91" width="300">

**Comment by antiero** [comment]
Got that working, amazing, thanks 🙏 Took me a while to figure out where to add this, because there wasn't a plist file for the UnitySwiftUI project! :) In the end, I went to Targets > UnitySwiftUI > Info, and added the CADisableMinimumFrameDurationOnPhone key there... which then created a separate Info.plist file in the UnitySwiftUI Xcode project - thanks again!

<img width="816" alt="Screenshot 2024-12-05 at 08 19 59" src="https://github.com/user-attachments/assets/8c14373b-8306-487b-96d4-a7f2f6535df5">
